name: pcn_erp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^1.0.0
  syncfusion_flutter_pdfviewer: ^18.4.41-beta

  webview_flutter_plus: ^0.1.1+10
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.0+2

  
  provider: ^4.3.2+2

  firebase_core: "0.5.0"  

  theme_provider: ^0.4.0+1

  onesignal_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/ajah.jpg
    - assets/moder2.jpeg
    - assets/pdf/efik-hymn.pdf
    - assets/pdf/Ajah.pdf
    - assets/igbo/main.css
    - assets/igbo/jquery.mobile-1.4.3.min.js
    - assets/igbo/jquery.mobile-1.4.3.min.css
    - assets/igbo/jquery-2.1.0.min.js
    - assets/igbo/index.html
    - assets/igbo/abu1.html
    - assets/igbo/abu2.html
    - assets/igbo/abu3.html
    - assets/igbo/abu4.html
    - assets/igbo/abu5.html
    - assets/igbo/abu6.html
    - assets/igbo/abu7.html
    - assets/igbo/abu8.html
    - assets/igbo/abu9.html
    - assets/igbo/abu10.html
    - assets/igbo/abu11.html
    - assets/igbo/abu12.html
    - assets/igbo/abu13.html
    - assets/igbo/abu14.html
    - assets/igbo/abu15.html
    - assets/igbo/abu16.html
    - assets/igbo/abu17.html
    - assets/igbo/abu18.html
    - assets/igbo/abu19.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html
    - assets/igbo/abu4.html



  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
